name: hello_bots
on: [push]
env: 
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install slack-sdk
          
      - name: Run script
        env: 
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        run: |
          echo $SLACK_API_TOKEN
