name: trans_bot
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install slack-sdk
          pip install arxiv
          pip inntall 'googletrans==3.1.0a0'
          
      - name: Run script
        env: 
          SLACK_API_TOKEN: ${{ secrets.G_TRANS_TOKEN }}
        run: |
          python translation_byGoogletrans.py
