name: trans_bot
on:
  schedule:
    - cron: '0 21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install slack-sdk
          pip install arxiv
          pip install 'googletrans==4.0.0rc1'

      - name: Run script
        env:
          G_TRANS_TOKEN: ${{ secrets.G_TRANS_TOKEN }}
        run: |
          python translate_byGoogletrans_v2.py
